client/cli/common/assignment.py
client/cli/ok.py
client/exceptions.py
client/sources/common/core.py
client/sources/doctest/__init__.py
client/sources/doctest/models.py
client/sources/ok_test/__init__.py
client/sources/ok_test/models.py
client/utils/format.py
tests/cli/common/assignment_test.py
tests/protocols/grading_test.py
tests/sources/common/core_test.py
tests/sources/common/doctest_case_test.py
tests/sources/doctest/models_test.py
tests/sources/ok_test/concept_test.py
tests/sources/ok_test/doctest_test.py
tests/sources/ok_test/models_test.py

Changelog:
* OK now errors if no tests were able to be loaded. If a single test source is not able to be loaded (e.g. can't find `hw01.py`), but other tests can be loaded, no error occurs (although a debug message is printed). This is to accomodate labs, where a student might have downloaded `lab02.py` but not `lab02_extra.py`; OK shouldn't exit prematurely just because it can't find `lab02_extra.py`
* Fix/add tests and make exceptions more consistent/informative
* Fix some bugs introduced in v1.3.2
* Resolve #19 
* Allow http requests to be sent even if assignment fails to load or protocols fail to run to completion.

Various updates, mainly bug fixes and updating tests

---

client/__init__.py
client/cli/common/assignment.py
client/cli/ok.py
client/sources/doctest/__init__.py
tests/cli/common/assignment_test.py

The old config for doctest sources required each doctest to be specified explicitly:
"hw1.py:square": "doctest",
"hw1.py:double": "doctest"
This PR allows staff to simply specify the filename, and all the doctests in that file will be loaded:
"hw1.py": "doctest"
Both formats are supported.

Allow all doctests in a file to be loaded

---

client/utils/network.py

Client now prints out the following if server connection times out:
```
Backing up your work...
Connection to server timed out after 1000 milliseconds
Unable to complete backup.
```
I also changed the `TIMEOUT` to 1000 milliseconds instead of 500 milliseconds.

Add error message if server connection times out

---

client/sources/ok_test/concept.py
client/sources/ok_test/doctest.py
client/sources/ok_test/models.py
tests/sources/ok_test/models_test.py

When locking tests, suites that are empty will be removed. This might arise if all the test cases in a suite are hidden -- all the hidden cases will be removed, leaving an empty suite. The empty suite will then be removed as well.
This is an alternative solution to #11 . This minimizes the number of fields staff members have to keep track of.
Resolves #11 .

Remove empty suites from ok_tests

---

client/cli/ok.py

* For loading errors, print out the string of the exception to get more information
* Only print the submission URL if --submit is used. Resolves #52 .
* Remove the "Backup successful message", since it caused confusing messages like
Backing up your work...
Unable to complete backup.
Backup successful.

Minor modifications to printed messages

---

client/cli/ok.py

Resolves #54 . `--backup` is functionally equivalent to `--submit` in that it offers reliable backups. The only difference is that the assignment is not marked as a submission.

Add --backup flag to cli

---

client/sources/doctest/models.py
tests/sources/doctest/models_test.py

Previously, the following doctest would be parsed incorrectly:
>>> print('1\\n  2')
1
2
The leading indentation on the "2" would be stripped. This PR fixes the issue by stripping only the leading whitespace common to all lines.

Fix doctest parsing bug involving leading whitespace in output

---

client/sources/common/doctest_case.py
tests/sources/doctest/models_test.py

Previously, there was a bug in doctest parsing for printed output:
>>> def foo():
...     print('hi')
...     return 1
>>> foo()
hi
1
This would cause an extra blank line to be inserted between the `hi` and the `1`. This is because printing always prints a newline by default, but the client code was adding another newline after that. The fix is to remove the added newline.

Fix print-then-return doctest bug

---

client/utils/auth.py

I'm trying to use ok-client as a git submodule in the ok-scripts repo for authentication. When I would try to import auth, I get the following. 
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/moowiz/src/ok-scripts/ok_client/client/utils/auth.py", line 3, in <module>
from client.utils.sanction import Client
ImportError: No module named 'client.utils.sanction'
```
Adding this relative import fixes this issue.

Fixed import so auth can be used through git submodules.

---

client/cli/ok.py
client/sources/common/interpreter.py
client/sources/ok_test/__init__.py
client/sources/ok_test/scheme.py
client/sources/ok_test/sqlite.py
demo/scheme/tests/q1.py
demo/sqlite/config.ok
demo/sqlite/hw1.sql
demo/sqlite/tests/q1.py

This PR adds an OK-style test for sqlite. OK will check that the installed version of sqlite3 is 3.8.3 or higher (this version includes the `with` statement).
Output for sqlite tests is **not** in sorted order. For example,
```
sqlite> select * from colors;
red
yellow
blue
```
Valid output could also be in the order `red, blue, yellow`, since the sqlite database does not enforce any particular order when doing `SELECT` statements. Accordingly, OK will first convert all actual and expected output into sets, and then compare the sets.
Currently, the only dot-command that is supported is `.read`.

Add sqlite integration

---

client/sources/ok_test/models.py
client/sources/ok_test/sqlite.py

1. If the Python sqlite3 module has an up-to-date binding (compared to
self.VERSION), interpret line-by-line with full output validation.
2. Otherwise, if there is an executable called "sqlite3" (in the current
directory is okay), pipe the test case into sqlite3 and display
expected and actual output. No output validation is available;
students have to verify their solutions manually.
3. Otherwise, report an error.
Please test this out manually before deploying.

Attempt to pipe test case to sqlite3 if Python bindings are not up-to-date

---

client/__init__.py
client/sources/scheme_test/__init__.py
client/sources/scheme_test/models.py
demo/scheme/config.ok
demo/scheme/hw1.scm

Port [scheme_test.py](http://inst.eecs.berkeley.edu/~cs61a/fa14/proj/scheme/scheme_test.py) from CS 61A.
To specify a scheme test, add the following to the .ok config file:
```
tests: [
...
"tests.scm": "scheme_test"
]
```
The output and test summary are exactly the same as in `scheme_test.py`. @brianhou , can you test this out to see if there are any issues?

Add scheme_test source

---

client/protocols/export.py

I forgot to check if a student subdirectory (within `submissions`) already exists before creating it. This fixes #84.

Only creates subdirectory for student if it doesn't already exist. Fixes #84

---

client/protocols/scoring.py
client/sources/common/models.py
tests/protocols/scoring_test.py

Partners are now specified in OK test files as strings, not ints:
```
test = {
...
'partner': 'A'
}
```
Test files with no 'partner' field specified will have their scores applied to all partners (this behavior was already present)
The output looks like this ("Partner " is prepended to each partner name):
```
Score:
Partner A: 31.0
Partner B: 31.0
```
Here's the output if an assignment has no partners:
```
Score:
Total: 14.0
```

Change partner labeling to strings instead of ints

---

client/protocols/grading.py
client/sources/ok_test/doctest.py
client/sources/ok_test/models.py
client/utils/format.py
tests/protocols/grading_test.py
tests/sources/ok_test/models_test.py

Resolves #96 and #98. The command line options remain the same:
```
python3 ok -q question_name -u
python3 ok -q question_name
```
However, if the `-u` flag is specified, `GradingProtocol` does not get run. In addition, GradingProtocol stops at the very "first" failed test case.

Stop on first failed test case; don't grade right after unlocking

---

client/protocols/unlock.py
tests/protocols/unlock_test.py

This implements @papajohn's proposal in #59.

Answer evaluation in UnlockProtocol

---

client/cli/common/assignment.py
client/protocols/unlock.py
client/sources/common/interpreter.py
client/sources/common/models.py
client/sources/doctest/__init__.py
client/sources/ok_test/__init__.py
client/sources/ok_test/concept.py
client/sources/ok_test/models.py
client/sources/ok_test/wwpp.py
client/sources/scheme_test/__init__.py
tests/protocols/unlock_test.py
tests/sources/common/interpreter_test.py
tests/sources/doctest/load_test.py
tests/sources/ok_test/models_test.py

@papajohn @ksteph 
This implements the recording of UnlockProtocol attempts. The structure of `messages['unlock']` (data collected by the UnlockProtocol` is the following:
```
{
string (test name):  [
{
"question timestamp": string (format "YYYY-MM-DD HH:mm:ss.microseconds"),
"answer_timestamp": string (format "YYYY-MM-DD HH:mm:ss.microseconds"),
"question": string,
"answer": list of strings (answers may contain multiple lines),
"correct": boolean
},
...
]
}
```
Each test is mapped to a list of unlocking attempts. Note that each Test contains multiple test Cases -- these are the "attempts" that are being recorded. We decided at our meeting that recording the question prompt is okay, but it might be ambiguous what a "prompt" is for Cases that prompt the user multiple times:
```
>>> 4 + 5
? …
```

Record unlocking attempts

---

client/protocols/backup.py
client/utils/network.py
client/utils/software_update.py
demo/ok_test/config.ok

It turns out `urllib.request.urlopen`'s timeout is specified in seconds, not milliseconds. ok-client has been assuming it's in milliseconds for a long time now. Oops.

Change urlopen timeout to seconds instead of milliseconds

---

client/cli/common/assignment.py
client/cli/ok.py
client/config.ok
demo/doctest/config.ok
demo/ok_test/config.ok
tests/cli/common/assignment_test.py

Resolves #100 .
Staff members can specify an optional "default_tests" field in `*.ok`:
```
"tests": {
...
},
"default_tests": [
"square",    // The string that students would input on the command line to specify this test
...
]
```
When `ok` is run without any `-q` flags, only tests in the `default_tests` list are run. I added an `--all` flag that allows students to run **every** test, not just the default tests.

Allow staff to specify default tests

---

client/cli/ok.py
client/protocols/export.py

As discussed in [ok#493](https://github.com/Cal-CS-61A-Staff/ok/issues/493), this adds an additional option to `ExportProtocol` to download the latest submission for each student rather than their final submission. The default behavior for `--export` is unchanged, but adding the `--latest` flag will download latest instead of final submissions.

Adds option to ExportProtocol to download latest instead of final submissions

---

client/cli/ok.py
client/protocols/backup.py
client/utils/software_update.py

500 milliseconds per request is most likely too short, because it prevents some students from being able to send final submissions when they have slow internet connection.

Change timeout on backup to 2 seconds

---

client/sources/common/interpreter.py

The case_id was inconsistent because the `prompt_num` variable would not be incremented if a prompt was already unlocked. The fix is to increment it in all cases.

Fix case_id construction bug

---

client/sources/common/pyconsole.py

The traceback scraper used to look for `<module>`, but that string doesn't always appear. This meant that rfind was returning -1, which was unchecked. This update essentially looks for `<string>.*\n` and only keeps the lines after the match.
Tracebacks can either be of the form
```
<stuff>
File "<string>", line 1, in <module>
<desired traceback>
```
if the error happens in student code, or
```
<stuff>
File "<string>", line 1
<desired traceback>
```
if the error happens in test code.

Make traceback scraping more robust to test errors.

---

client/__init__.py
client/sources/doctest/__init__.py
tests/sources/doctest/load_test.py

This PR allows us to reference a method's doctests directly, rather than by duplicating the code in a separate ok_test file. Valid test names now include names of the form `foo.py:Foo.bar`.

Add support for doctest names with dots.

---

.gitignore
client/protocols/backup.py

There's currently no way to force a submit. The default timeout is 15 seconds.
See https://piazza.com/class/id52tzq2i7yfx?cid=2747 for this issue in the wild.

No timeout for --backup and --submit

---

client/sources/scheme_test/models.py

Add missing output.on() so useful Python error messages are printed.

Resolve issue with Python errors being silenced in Scheme tests

---

.gitignore
client/sources/ok_test/sqlite.py
demo/sqlite/tests/q1.py
env/pyvenv.cfg

Before:
```
TEST:
.read lab12.sql
SELECT * FROM obedience LIMIT 10;
EXPECTED (order does not matter):
7|Image 1
7|Image 2
Choose this option instead.|Image 2
7|Image 5
Choose this option instead.|Image 5
7|Image 5
7|Image 2
7|Image 4
I'm a rebel|Image 4
YOLO!|Image 5
OUTPUT:
7|Image 1
7|Image 2
Choose this option instead.|Image 2
7|Image 5
Choose this option instead.|Image 5
7|Image 5
7|Image 2
7|Image 4
I'm a rebel|Image 4
YOLO!|Image 5
Please manually check if your solution's output is correct.
```
After:
```
sqlite> .read lab12.sql
sqlite> SELECT * FROM obedience LIMIT 10;
7|Image 1
7|Image 2
Choose this option instead.|Image 2
7|Image 5
Choose this option instead.|Image 5
7|Image 5
7|Image 2
7|Image 4
I'm a rebel|Image 4
YOLO!|Image 5
```

Automatically compare test output when using local ./sqlite

---

client/exceptions.py
client/utils/auth.py

A small but significant number of students have issues with finding a free port when authenticating.
I don't know how to reproduce this issue, so I'm not 100% sure if this PR will help, although the student that provided the above screenshot was able to find an open port with `s.bind(('localhost', 0))`.
I'm also not sure if looking for an open port is always necessary -- it seems that this should only be happening when authentication actually happens.

Resolve authentication issues*

---

client/__init__.py
client/cli/ok.py
client/protocols/backup.py
client/sources/ok_test/__init__.py
client/sources/ok_test/sqlite.py
client/utils/software_update.py

Change log: 
- Hotfix for sqlite3 module (on multiple withs?) See #140 
- Resolve #139 by catching all socket errors
- Longer timeouts for force updates (and normal updates as well) 
I will try to also include a fix for the socket timeout issue (#139) so future upgrades won't have issues. 
Merging & Publishing now since a lot of students are running into this issue.

do not use sqlite3 module, update socket timeout

---

client/protocols/backup.py
client/utils/auth.py

SSL was only checked in `backup.py`, but it seems like it should always be checked before authenticating? I'm not sure what problem this actually fixed though.

Check if SSL is installed before all authentication.

---

client/api/assignment.py
client/cli/lock.py
client/cli/ok.py
client/cli/publish.py
client/cli/test.py
client/protocols/grading.py
client/sources/common/interpreter.py
client/sources/common/models.py
client/sources/common/pyconsole.py
client/sources/doctest/models.py
client/sources/ok_test/doctest.py
client/sources/ok_test/models.py
client/sources/scheme_test/models.py
demo/ok_test/tests/q2.py
tests/api/assignment_test.py
tests/sources/doctest/models_test.py
tests/sources/ok_test/doctest_test.py
tests/sources/ok_test/models_test.py

Resolves #135 . @papajohn @SamLau95
Usage:
```python
>>> from client.api.assignment import load_assignment
>>> assign = load_assignment('hw1.ok')
>>> # setup environment for tests
>>> results = assign.grade('q1')
>>> results
{'passed': 0, 'failed': 5, 'locked': 0}
>>> # students write some code to change the environment
>>> assign.grade('q1')
{'passed': 5, 'failed': 0, 'locked': 0}
```
Notes:
* `grade` takes a keyword argument `env` that is a `dict` representing the environment in which to execute the tests.
* If `env` is not specified, OK will use the environment of `__main__`. This is **not** necessarily the caller of `grade`. For example,
```python
def fn():
x = 4
assign.grade('q1')  # Will not have access to x
```
* The 'ok' binary has to be available on `sys.path`. You can either add …

Add programmatic API for grading

---

client/sources/ok_test/sqlite.py
demo/doctest/config.ok
demo/doctest/hw1.py
demo/sqlite/tests/q3.py

I haven't tested that this correctly terminates the sqlite subprocess when it takes too long.
This should be merged after #146. Resolves #140.

Use subprocess timeout for SQL

---

client/cli/ok.py
client/exceptions.py
client/utils/auth.py

Hides the tracebacks and prints a more user-friendly message when authentication fails under different scenarios (authorization code not received, access token is None). Addresses #152.

Catch authentication errors

---

client/utils/auth.py

This resolves #157. On Unix, the auth token is now stored in `~/.config/ok/auth_refresh` while on Windows it's stored in `C:\Users\<user>\AppData\Local\ok\auth_refresh`.
I've tested this on Linux. Someone else should test it on Windows.

Stores auth token in persistent config directory

---

client/sources/ok_test/doctest.py

It seems like `env` expects a None value 
>         env          -- dict; environment in which to run tests. If None, an
empty dictionary is used instead.
Making None be the default value for env in `DoctestSuite` fixes the scoring protocol
Old error when running the scoring protocol: 
```
Traceback (most recent call last):
File "ok/__main__.py", line 9, in <module>
File "ok/client/cli/ok.py", line 132, in main
File "ok/client/protocols/scoring.py", line 51, in run
File "ok/client/sources/ok_test/models.py", line 99, in score
TypeError: run() missing 1 required positional argument: 'env'
```

Fix Scoring Protocol 

---

client/cli/lock.py

Before, if `ok-lock` raised an exception, we'd get
```
$ ok-lock
Traceback (most recent call last):
File "/Users/knrafto/code/berkeley-cs61a/env/lib/python3.4/site-packages/client/cli/lock.py", line 31, in main
assign = assignment.load_assignment(args.config, args)
File "/Users/knrafto/code/berkeley-cs61a/env/lib/python3.4/site-packages/client/api/assignment.py", line 19, in load_assignment
config = _get_config(filepath)
File "/Users/knrafto/code/berkeley-cs61a/env/lib/python3.4/site-packages/client/api/assignment.py", line 37, in _get_config
raise ex.LoadingException('No .ok configuration file found')
client.exceptions.LoadingException: No .ok configuration file found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Fix ok-lock NameError

---

client/__init__.py
client/cli/ok.py
client/protocols/hinting.py

Multiple students have asked for a way to turn hints off because having it ask on every run of ok can be annoying. 
This PR makes it ask at most every 5 attempts and also includes the `--no-hints` CLI flag to completely disable hints.

Do not prompt for hints on every attempt

---

client/sources/ok_test/models.py

This is just a quick and dirty fix in regards to #134. We write to a temporary file (non-atomic) and replace the existing test file with our temp file, so even if the client is interrupted the test cases won't get corrupted. Note that this only works on Unix systems; there's no way to guarantee an atomic file write on Windows, so I suggest we start looking into other ways to prevent this situation from even taking place.
1. Disable interrupts during test dumps. This is probably the best solution, and I'll look into implementing this.
2. Instead of modifying the tests, we can write to a separate file that contains unlocked test data. Note that this won't solve the issue of corruption, but it's an easier fix (delete the corrupted tests) than re-downloading the archive just to copy one test …

Perform atomic test dumps

---

client/__init__.py
client/utils/guidance.py

`FileNotFoundError` is 3.3+ so we'll catch `OSError` instead.

Catch File Not Found Errors for Guidance

---

client/__init__.py
client/protocols/backup.py
client/protocols/unlock.py
client/utils/auth.py

Change: 
- Use 127.0.0.1 instead of localhost to resolve DNS/Network issues 
- Only get port when authenticating instead of always
- Use default 6165 (bonus points for figuring why its 6165)
- add --get-token flag
- better error handling (actual error pages), instead of just exceptions in the terminal 
Ideally someone could test this on linux & windows. 
Test Suite: 
- Auth with `--auth` 
- Auth with another process using the default port (`python3 -m http.server --bind 127.0.0.1 6165`) 
- Auth but you hit the deny button on the OAuth permissions screen

Improve Auth Error Handling  (--get-token, error messages)

---

client/__init__.py
client/sources/ok_test/__init__.py
client/sources/ok_test/logic.py

There's quite a bit of duplicated code between `client/sources/ok_test/logic.py` and `client/sources/ok_test/scheme.py` that should perhaps be refactored, but I was in a rush to get this out for the lab. This works, but I'm working on updating the Logic executable and lab so that @Sumukh can try it out from a real assignment.

Implement Logic OK tests.

---

client/__init__.py
client/sources/ok_test/logic.py

If `(load logic_file)` is run several times, the facts within that Logic file are appended to the global list of facts several times, resulting in duplicate facts and therefore duplicate outputs.
This PR resets the state of the Logic interpreter between suites by clearing the list of facts at the beginning of each suite run.

Fix persistence "bug" when running multiple Logic suites.

---

client/cli/ok.py

Reverts Cal-CS-61A-Staff/ok-client#216
This causes issues for some who don't have trouble with 32 but python.

Revert "Warn and exit on 32 bit installations of Python"

---

client/protocols/unlock.py
tests/protocols/unlock_test.py

Changes unlocking to use ast.literal_eval

---

.travis.yml

We might want to think about deprecating 3.2 support.

Add Python 3.6 to tests

---

client/__main__.py

Resolves #218. Example output:
```
$ python2 ok
ERROR: You are using Python 2.7, but OK requires Python 3.3 or higher.
Make sure you are using the right command (e.g. `python3 ok` instead of
`python ok`) and that you have Python 3 installed.
```

Require version 3.3 or higher

---

client/protocols/autostyle.py
client/protocols/backup.py
client/protocols/collaborate.py
client/protocols/hinting.py
client/utils/auth.py
client/utils/guidance.py
client/utils/software_update.py
requirements.txt
tests/utils/software_update_test.py

Resolves #232.
I removed all references to `urllib.request`. I tried to test everything manually as I changed them. Hopefully we'll have less SSL errors now that we use requests' certs.

Use requests

---

client/cli/ok.py
client/protocols/hinting.py
client/protocols/unlock.py
client/utils/guidance.py
client/utils/prompt.py
tests/protocols/unlock_test.py

This adds a feature to the unlocking guidance messages where we prompt students for an explanation of their answer. This allows the guidance researchers to understand _why_ students are leaving certain answers. It can also be useful for students to be able to explain their answers. 
The changes to provide the watchlist are tacked on to the existing guidance messages files and the collected responses goes into the unlocking message (just like the other guidance fields) 
Some details:
- There are treatment groups - this is handled by the old treatment code for the most part. 
- It asks only if the student answers is a watchlist or if they were randomly selected to answer their correct answer. 
Ship date: Shipping before first CS61A Lab this week (if the `.ok_guidance` file is updated)

Guidance Prompt for Explanation

---

client/__init__.py
client/utils/auth.py

I'm not sure how I got into a situation where my token couldn't be refreshed - but if someone does we should have them auth again. 
I only put it in the notebook code because it immediately accesses the email on every call to auth - unlike the normal auth flow.

Retry expired logins in notebooks

---

client/api/assignment.py
client/protocols/backup.py
tests/api/assignment_test.py

From now on we'll ignore the list of protocols in `protocols`.

Always load all protocols

---

client/sources/doctest/__init__.py

Specifying doctests as
```
"tests": {
"hw04.py": "doctest"
}
```
is supposed to load all doctests from a file, but it would miss doctests on class methods. Using the power of recursion we can now see everything.
Tested with http://cs61a.org/hw/hw04/
Before:
```
> python3 ok --tests --no-update
=====================================================================
Assignment: Homework 4
OK, version v1.10.1
=====================================================================
Available tests:
balanced
branches
centered_interval
end
examples
interval
is_leaf
is_tree
is_weight
label
length
make_anonymous_factorial
make_counter
make_fib
mobile
move_stack
print_move
side
sides
size
total_weight
tree
weight
with_totals
```
After:
```
> python3 ok --tests --no-update …
```

Find doctests recursively so class methods are loaded

---

client/protocols/backup.py
client/utils/auth.py
demo/ok_test/config.ok

Resolves #286 
The only thing that now uses access tokens as query parameters is collaborate - but the collab server isn't equipped to accept auth tokens through headers.

Use Auth Header (Bearer Token)

---

client/protocols/scoring.py
tests/protocols/scoring_test.py

ok-client had the ability to score partners of a project differently. It was confusing and nobody currently uses it, so I'd rather remove it than document it

Remove partner scoring system

---

.gitignore
README.md
release.py

Resolves #264, #276.
Test plan:
* Clone into a new github repo for testing
* Comment out the `python setup.py sdist upload`
* Edit `GITHUB_REPO` to point to the testing repo
* Edit `OK_SERVER_URL` to point to `localhost:5000`
* Try to "release" the fake client. Should see
* Version bump pushed to github
* GitHub release with correct binary
* Updated client version on localhost:5000

Script to release ok-client

---

client/__init__.py
client/utils/auth.py

All requests to get_info (when we tried to get emails) were failing. 
Discovered when `--collab` stopped working (because it didn't get the emails)

Use correct header for OK auth

---

client/sources/common/interpreter.py
client/utils/output.py
demo/doctest/config.ok
demo/doctest/hw1.py
demo/ok_test/tests/q1.py
tests/sources/common/pyconsole_test.py
tests/utils/output_test.py

This changes how exceptions in doctests and OK tests are handled to match the [doctest module's exception handling](https://docs.python.org/3/library/doctest.html#what-about-exceptions). In addition to
```
>>> raise ValueError('hello')
ValueError
```
you can also write
```
>>> raise ValueError('hello')
Traceback (most recent call last):
...
ValueError: hello
```

Emulate doctest exception handling

---

.gitignore
.travis.yml
client/api/assignment.py
client/protocols/rate_limit.py
tests/protocols/rate_limit_test.py

Added a new protocol `rate_limit` that handles rate-limiting per question (requested by 61A su17 course staff).
Current backoff is None for attempts 1-2, 3min for attempt 3, and 5min for attempts 4+.  (Open to opinions - can easily be changed by modifying `BACKOFF` in the `rate_limit.py` file.)
Notable implementation details:
- uses `hmac` and `shelve` builtin libraries for secure persistence
- should resist tampering with the `.ok_storage` file where rate-limit data is stored
- should also resist redownloading assignment to circumvent rate-limiting

Add per-question rate limiting

---

client/api/assignment.py

Resolves #310 
Changelog:
- add new `Settings.update` method that mutates Settings object with new settings
- call this method in `set_args` instead of `self.cmd_args = Settings(...)` as before
Proper submitting for data8 should work now.

mutate Settings when calling `Assignment.set_args`

---

client/exceptions.py
client/utils/auth.py

- Catches Errors pertaining to non-ASCII hostnames (e.g. when a hostname has non-english characters)  #309, #181 
- Auto fallback to browser less auth when browser-based auth fails
- Add better logging for exceptions, so we can debug more easily using `--debug`

Catch and Handle More Auth Exceptions

---

client/protocols/rate_limit.py
tests/protocols/rate_limit_test.py

Converts rate limiting into more of a lightweight hint system so it will hopefully cause less irritation by now suggesting a task and setting the cooldown as a function of the expected task length. In addition, the system gets out of the way with more freebies.
Resolves #317 and #318.

Add simple hints to rate limiting

---

client/protocols/rate_limit.py

Bump `RETRY_MSG` usage starting from 0.1 of the cooldown period to 0.5 of the cooldown period.

Tune rate limiting RETRY_THRESHOLD

---

client/utils/auth.py

This PR fix a issue common in DS100 assignment notebooks.
When students encounter `ok.auth()`, they either have no issue
logging in or they encounter an Oauth error, which they have
to use `ok.auth(force=True)` to force authenticate.
This PR does just one thing: it catches the OAuthException and
redirect to the `ok.auth(force=True)` version. Thus student
don't have to guess which command to put in.
Technically, I
- remove the error logging message that will show up in notebook.
- catch the OAuthException and return a `force=True` version of it.
<Simon Mo>

Fix OAuthException in notebook_authenticate

---

client/utils/auth.py

Fixes auth typo from #333 
Signed-off-by: Colin Schoen <cschoen@berkeley.edu>

Fixes typo in auth docstring

---

client/sources/ok_test/scheme.py

Resolves #342.
This ensures that `#t` and `#f` are displayed correctly in all tests. It depends on version 1.2.3 of the Python-based Scheme interpreter (release in progress on staff repo).

Use `repl_str` in SchemeConsole

---

client/cli/publish.py

The proper check for `virtualenv` (and also the extension to support `venv`) isn't via the environment variable but rather via checking `sys`, as explained [here](https://stackoverflow.com/a/42580137), so I've changed that.
Finding `site-packages` should also not be done manually; I've replaced it with `distutils.sysconfig.get_python_lib` which I believe is the correct call.

Correct the check for site-packages and virtualenv

---

client/sources/ok_test/models.py
client/utils/storage.py

Seems I'd completely [left out](/okpy/ok-client/commit/7e54ff4241a7ce0fbf77241b67f69e5fdc66196a#diff-7cbfa67907b35a53193c0bb467d224c1R15) the last two arguments to [`CreateTransaction`](https://docs.microsoft.com/en-us/windows/desktop/api/ktmw32/nf-ktmw32-createtransaction) for some reason.
I [added them back in](/okpy/ok-client/pull/366/commits/33ad43c1e92dd14b3e26df02f2d8ef5d3482f581#diff-7cbfa67907b35a53193c0bb467d224c1R15) and fixed the issue. Also tested it on 32-bit Python and it works fine.
Previous link: #365

Transactional rename on Windows

---

client/api/notebook.py

Fixes #359. 
Previously, JupyterLab's removal of the IPython object in JavaScript affected our ability to call ok.submit() in code. The solution is to directly trigger the frontend save button's click() method with the following snippet: `document.querySelector('[data-command="docmanager:save"]').click();`.
I've also added code to allow selection of each mode via a parameter (default is normal Jupyter Notebook). The reason this isn't done in code is it's difficult to determine reliably which frontend an IPython kernel is running inside.

Add code to support JupyterLab saving

---

client/api/notebook.py

Fixes #352 
Clarification of issue: users working on a different file from the one specified in config get cryptic error messages during ok.submit(), and the wrong file is submitted (the case where the file in config doesn't exist throws an error).
Detecting the current notebook name in Jupyter is difficult/unreliable. Instead, this PR provides a more descriptive error message and warns the user that the current submission may not be the current file they are working on. The ok client still attempts to submit the file that is specified in the configuration (as the submit method should).

Improved clarity for submission error when wrong file is saved

---

tests/end_to_end/smoke_test.py

This successfully catches issues like the cacert.pem issue that happens when we upgrade requests

Add quick smoke test

---

client/utils/output.py

Outputting Unicode on Windows can result in an error since the default encoding for `open()` (`cp1252`) can be different from that of stdio. Here we make it match that of the underlying stream.
For earlier Python versions it would also be necessary to change the default encoding for stdio to `utf-8`, but I avoided doing that here since the default appears to have been already changed to UTF-8 as of Python 3.7(?).

Fix output encoding mismatch

---

.github/workflows/main.yml
client/protocols/unlock.py
client/sources/common/interpreter.py
client/sources/common/models.py
tests/protocols/unlock_test.py

Lets you add a `multiline=True` flag to cases. When this flag is present, the unlock protocol will always use the multiline protocol. This is needed when we have a question where multiline answers are _possible_, but the correct answer has just one line. Otherwise, students can look at the prompt to determine whether the answer has just one or multiple lines.
Test plan: `pytest testForceMultipleLineMultipleFailsBeforeSuccess`.

Add multiline=True flag to unlockable cases

---

.github/workflows/main.yml
requirements.txt

Python 3.6 adds f-strings which are now both used in OKClient and in CS61A assignments, and are generally super awesome. Cs61A currently recommends installing Python 3.9 so it seems safe to upgrade minimum version to 3.6.

Remove 3.5 support from CI

---

client/api/assignment.py
client/cli/lock.py
client/cli/ok.py
client/protocols/analytics.py
client/sources/common/interpreter.py
client/sources/common/pyconsole.py
client/sources/doctest/__init__.py
client/sources/doctest/models.py
tests/sources/common/interpreter_test.py

Sorry that we went back and forth on this, but we realized that FPP is an acronym that only our own group uses, while "Parsons Problems" (or "Faded Parsons") are what everyone else recognizes. So this PR rids the OSS world of one more unnecessary obscure acronym.
I realize this affects multiple PRs in the cs61a repo and I will check them out with this change next. (After watching the results of this CI test).

Rename fpp to parsons

---

client/sources/common/interpreter.py

Emojis seem to be causing issues on some machines, so this PR replaces them with simple emoticons instead. A change already made in faded-parsons replaces the emoticons in the Parsons runner with the emojis.
Terminal output:
Parsons runner:

Don't use emojis

---

client/sources/common/interpreter.py
tests/sources/common/pyconsole_test.py

earlier, when we had an infinite loop, we would not increment the total case count. As a result, when a student timed out on the second test case, the parsons tool would receive {passed: 1, total: 1} and incorrectly display that all test cases passed.

Fix: always increment total case count

---

client/utils/auth.py

Currently, `ok-client` doesn't acknowledge the fact that the `refresh_token` changes when used. This means that after the first automatic token refresh, a subsequent refresh will require manual approval (since the token will be incorrect). This PR should fix this issue.

Fix: refresh the refresh_token

---

client/protocols/backup.py

Previously, the backup URL only showed when students ran `python3 ok --submit` or `python3 ok --backup`. Per #467, we should show the URL when any backup is made (such as when running `python3 ok`! IMO this is good, but can adjust the wording to something similar to #467 if @pamelafox prefers.
This is what it looks like:
```
=====================================================================
Assignment: Homework 1
OK, version v1.18.1
=====================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests
---------------------------------------------------------------------
Question 2 > Suite 2 > Case 1
>>> from hw1 import *
>>> double(3)
3
Run only this test case with "python3 ok -q q2 --suite 2 --case 1" …
```

show backup url whenever a backup is made

---

client/sources/doctest/__init__.py

Class decorators are currently causing recursion errors due to the load_tests recursive logic, and the fact that a bound method refers back to the original class in both the self and im_self attributes.
This adds a condition to ignore those attributes.
Example problematic code before:
```
class RandomCat:
"""
Returns a new instance of a Cat with the given owner,
a randomly chosen name and a random number of lives.
>>> randcat = RandomCat.adopt_random_cat("Ifeoma")
>>> isinstance(randcat, RandomCat)
True
>>> randcat.owner
'Ifeoma'
"""
cat_names = ["felix", "bugs", "grumpy"]
def __init__(self, name, owner, lives=9):
self.is_alive = True
self.name = name
self.owner = owner
self.lives = lives
@classmethod
def adopt_random_cat(cls, owner):
cat_name = RandomCat.cat_names[len(owner) % …
```

Dont recurse on self/im_self

---

client/sources/scheme_test/models.py

- `end_of_line` and `pop_first` functionality, since `Buffer` now yields an `EOL_TOKEN` (end of line token) at the end of every line.

scheme_test: update to work with sp22 cs61a Buffer class
