client/utils/network.py
=> Display correct submission URL

client/cli/common/assignment.py, client/cli/ok.py, client/cli/test.py, client/sources/common/doctest_case.py, client/sources/doctest/models.py, tests/cli/common/assignment_test.py, tests/sources/common/doctest_case_test.py, tests/sources/doctest/models_test.py
* Resolves #38 ; errors in teardown code now fails gracefully. Also, teardown code is not run if setup code fails, to mimic `unittest` behavior.
=> Various bug fixes

client/__init__.py, client/sources/ok_test/sqlite.py
I don't know how to deploy a new version of the `ok` client with this change.
=> sqlite version warns instead of errors

client/cli/ok.py, client/config.ok, client/protocols/backup.py, client/protocols/file_contents.py, client/protocols/grading.py, client/protocols/restore.py, tests/protocols/file_contents_test.py, tests/protocols/grading_test.py
I've implemented `RestoreProtocol` based on Option B (as discussed on #81) as it seemed to strike the right balance between preserving student data and convenience.
=> Adds ability to restore from a previous backup

client/cli/ok.py, client/cli/test.py
=> Make ok-test and ok share the same command line arguments

client/protocols/export.py
=> Fix export --latest bug

client/protocols/analytics.py, tests/protocols/analytics_test.py
See issue #113 ; I changed the regex as discussed in the issue. Also added a new regex to support default code detection in scheme project.
=> Fixed bug in AnalyticsProtocol; added scheme support

client/utils/html.py
=> Localhost auth page fix

client/utils/timer.py, tests/utils/timer_test.py
=> Evaluate student code in main thread when timeout is zero.

client/sources/doctest/__init__.py, tests/sources/doctest/load_test.py
Resolves #128, but could use more testing.
=> Add additional check when loading tests to only load tests from the file to be tested.

client/sources/ok_test/sqlite.py, demo/sqlite/tests/q2.py
Addresses the cleanup suggested in #136 and #140, removing traces of pysqlite.
=> Remove dead code from sqlite implementation.

client/sources/ok_test/__init__.py, client/sources/ok_test/models.py
I think this resolves #150, but I'm still trying to look through the code to make sure that this is an actual fix.
=> Fix bug with reloading tests via API.

client/cli/ok.py
=> Added warning for 32bit Python

client/utils/guidance.py
One line code change to have not quite try again print out after the targeted guidance message is shown. @ksteph @knrafto
=> Added not quite try again after printing out guidance message

client/__init__.py, client/protocols/analytics.py, client/protocols/hinting.py
Changes to Ok:
* The analytics protocol now keeps track of the number of attempts per question and overall. This info is included in the analytics messages (and stored locally as `.ok_history`) 
* `analytics` should be run after the `grading` protocol for full functionality
Additions:
* Hint generation protocol: It queries the server for changes and displays hints along the lines of: 
> The computer thinks that the conditional expression on line 4 has some errors.
It also provides rubber duck debugging prompts to help guide students to solve questions themselves. 
The prompts are along the lines of:
> What kinds of debugging strategies have you tried? [List of strategies]: 
> Could you describe what the error is for the computer?: 
(after hint is displayed and student corrects error) 
> …
=> Hint Generation Protocol

client/protocols/unlock.py, client/utils/guidance.py
Adds logging functionality to help debug. Also sends the student's email as well as assignment to the treatment group server when looking to get a treatment group number.
=> Logging for Guidance.py and sends assignment and email to treatment group server.

.gitignore, client/cli/ok.py, client/protocols/unlock.py, client/utils/guidance.py, demo/guidance_test/tests/.ok_guidance, tests/utils/guidance_test.py
The changes are here but I couldn't get it to produce any guidance messages - so it's likely that something went wrong - but I can't figure out where. 
Steps to merge: 
- to replicate: `python3 ok -u --debug --local` in a folder that I will send over.
=> Handle changes to Guidance Steps

client/__init__.py, client/cli/ok.py, client/protocols/autostyle.py
It looks like autostyle needs a bit more time to get the full system up - so I've offered to stub a protocol for them until they get the full system up.
=> Stub Autostyle Protocol

client/protocols/backup.py
=> Do not submit saved backups as submissions

client/__init__.py, client/cli/ok.py, client/protocols/analytics.py, client/protocols/hinting.py, client/utils/format.py
`--hint` will now request a hint. This avoids having to ask students on every attempt if they would like a hint. 
Every 5 attempts, a reminder that the hint command exists is printed. 
Examples:
Reminder to use hint (every 5 attempts):
```
python3 ok -q ordered
---------------------------------------------------------------------
Test summary
0 test cases passed before encountering first failed test case
---------------------------------------------------------------------
To get hints, try using python3 ok --hint -q ordered
---------------------------------------------------------------------
```
```
ok -q nodots --hint
...
nodots > Suite 1 > Case 3
scm> (load 'hw08)
scm> (nodots '((1 . 2) 3))
((1 . 2) 3 ())
---------------------------------------------------------------------
Test …
```
=> Hinting Protocol Improvements

client/cli/ok.py
Fixes #215 
Signed-off-by: Colin Schoen <cschoen@berkeley.edu>
=> Warn and exit on 32 bit installations of Python

client/__init__.py, client/cli/ok.py, client/protocols/collaborate.py
Stub `--collab` so we can add it in later in an update.
=> Bump to 1.7.1 and add stub for --collab

client/protocols/backup.py
=> Remove logging of access token

client/cli/publish.py, setup.py
This will install requirements recursively on berkeley-cs61a
=> Install requires

client/cli/ok.py, client/protocols/grading.py, client/sources/ok_test/__init__.py, client/sources/ok_test/concept.py, client/sources/ok_test/doctest.py, client/sources/ok_test/models.py, client/sources/ok_test/sqlite.py, client/sources/ok_test/wwpp.py, tests/sources/ok_test/concept_test.py, tests/sources/ok_test/doctest_test.py, tests/sources/ok_test/models_test.py
Still needs tests and a message to students telling them how to use it.
=> Adds support for running a single test case

client/protocols/collaborate.py
json.decoder.JSONDecodeError is new as of 3.5
=> [WiP] Collab bug fixes

client/cli/ok.py, client/protocols/backup.py, client/protocols/restore.py
=> Handle --local	 and network communication (Resolve #217)

client/protocols/backup.py, client/utils/auth.py, client/utils/network.py
Original: #230. Needs more testing
=> Catch SSL ImportError

client/cli/ok.py
=> Do not attempt to update with --local

client/__init__.py, client/api/assignment.py, client/api/notebook.py, client/utils/auth.py, demo/ipython/Submit to OK.ipynb, demo/ipython/ipy.ok, demo/ipython/ok_tests/q01.py, demo/ipython/ok_tests/q02.py
Resolves #261 
The changes are pretty minimal - I might merge & deploy depending on course requests.
=> Submit from iPython

client/protocols/analytics.py
=> Fix Analytics Question Name Bug

client/api/notebook.py, client/protocols/grading.py, client/protocols/scoring.py, client/sources/common/interpreter.py, client/sources/ok_test/concept.py, client/sources/ok_test/doctest.py, client/sources/ok_test/models.py, client/sources/ok_test/wwpp.py, client/utils/auth.py, tests/sources/ok_test/models_test.py
Changes to support autograding within notebooks. This should be deployed with another (#269) PR with modularized auth for notebooks. 
TODO Before Merge:
=> Scoring for notebooks

client/utils/guidance.py, client/utils/prompt.py
Tweaked the explanation messages a bit. Also, don't print "To help CS 61A provide better hints..." twice if they just hit enter.
=> Guidance tweaks

client/__init__.py, client/utils/guidance.py
Going to leave this open for a bit while we make sure there aren't more bugs.
=> Fix some bugs when not using propagation

client/__init__.py, client/api/notebook.py, demo/ipython/ipy.ok, tests/api/notebook_test.py
I was trying autosave out on JupyterHub and I noticed that I was getting blank files more often - so it looks like validation is needed.
=> Notebook autosave validate & retry

client/utils/guidance.py
Tested manually, it seems to work for hog.
=> Do not prompt for explanations if no guidance config

client/__init__.py, client/protocols/hinting.py
- Will bump the version after testing
=> Add sp17/hw07 to hinting

client/protocols/hinting.py
Going to bump the version number once I confirm that I don't need any more changes.
=> Hinting user identifier

client/utils/guidance.py
Collect answers outside of the watchlist too.
=> Collect rationale for some wrong answers too

client/api/assignment.py, client/api/notebook.py, client/cli/ok.py, client/protocols/autostyle.py, client/protocols/backup.py, client/protocols/collaborate.py, client/protocols/hinting.py, client/utils/auth.py, client/utils/guidance.py, release.py
Resolves #290. Tested submitting, notebook logging in, and `--get-token`.
=> Do not pass assignment to auth functions

README.md, release.py, setup.py
=> Replace Cal-CS-61A-Staff with okpy in URLs

client/protocols/testing.py, client/sources/common/pyconsole.py, client/sources/ok_test/scheme.py, client/utils/debug.py, tests/protocols/support_files/hw1.py, tests/protocols/support_files/mytests.rst, tests/protocols/testing_test.py, tests/sources/common/interpreter_test.py, tests/sources/common/pyconsole_test.py, tests/sources/doctest/models_test.py, tests/sources/ok_test/doctest_test.py
This should allow printf-style debugging in CS61A and other related 
courses
=> Add feature that allows for the usage of debug statements in doctested programs

client/sources/ok_test/models.py, client/utils/storage.py
This reverts commit 7e54ff4241a7ce0fbf77241b67f69e5fdc66196a.
=> Revert "Transactional rename on Windows (#355)"

client/sources/ok_test/sqlite.py
Adds support for a custom sqlite3 shell. Falls back to existing method if it doesn't exist.
=> Support sqlite shell

client/__main__.py, client/utils/locking.py, client/utils/storage.py, requirements.txt, setup.py
Should fix https://github.com/okpy/ok-client/issues/375
=> py38 compat fixes

client/__main__.py, client/utils/locking.py, client/utils/storage.py, requirements.txt, setup.py
Running into urllib3 issues and @kavigupta said to revert and he'll take a look later.
=> Revert "py38 compat fixes (#376)"

requirements.txt
This reverts commit 04ea6ad7ed37dd1110a37c97e42fdd371f5ef709.
=> Revert "Bump requests from 2.12.4 to 2.20.0 (#373)"

tests/protocols/unlock_test.py
Resolves https://github.com/okpy/ok-client/issues/380
=> Fix nosestests

client/api/assignment.py, tests/api/assignment_test.py
Should resolve https://github.com/okpy/ok-client/issues/364
=> Improve the error that happens when a question does not exist.

requirements.txt, setup.py
=> Revert "Bump requests to latest version"

client/__init__.py, client/cli/ok.py, client/protocols/help.py
- more feedback
- consent
- context
=> [fa23] hw09 get-help updates

client/protocols/help.py
=> [fa23] log no feedback
